# Generated by Django 4.2.4 on 2023-09-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sample_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sample',
            new_name='start',
        ),
    ]
